# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Build"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container:
      image: ubuntu
      options: --network-alias testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
      - run: npm i -g serve
      - run: serve -s build &
      - run: EXTRAS=--publish npm run testUI
        env: 
          SELENIUM_REMOTE_URL: http://hub:4444/wd/hub




