# This is a basic workflow to help you get started with Actions

name: Selenium Tests

# Controls when the action will run. 
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: "Build"
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - run: npm i -g yarn
      - run: yarn
      - run: yarn build
      - name: Upload build
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: build

  test:
    name: "TEST Selenium" 
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mohamnag/ubuntu-git
      options: --network-alias testHost
    services:
      hub:
        image: selenium/hub:3.141.59-gold
      firefox:
        image: selenium/node-firefox:3.141.59-gold
        env:
          HUB_HOST: hub
          HUB_PORT: 4444
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Use Node.js 
        uses: actions/setup-node@v1
        with:
          node-version: 15
      - name: Download build
        uses: actions/download-artifact@v2
        with:
          name: build
          path: build
      - run: npm i -g yarn
      - run: yarn
      - run: npm i -g serve
      - run: EXTRAS="--publish -t 'not @skipci'" npm run testUI
      
        env: 
          SELENIUM_REMOTE_URL: http://hub:4444/wd/hub


